### ISSUE TITLE
PA Review: Playing Songs

### ISSUE THREAD

**Issue by jonjonray** [jonjonray/LoudFog#5]
- [x] Progress bar appears at the bottom
- [x] Displays and plays music while navigating
- [x] Adequate Styling

**Comment by AAlfarho** [comment]
Great Job.
Couple of things to consider in regards to style.
+ How do you feel about the volume popping up?
+ The play/stop and volume, when hovering over them, they don't change the pointer to cursor, let's tackle that.

**Comment by AAlfarho** [comment]
Good job on new transition for both the volume bar and the media player itself.
MVP complete, kudos!
