### ISSUE TITLE
PA Review: Song CRUD

### ISSUE THREAD

**Issue by jonjonray** [jonjonray/LoudFog#6]
- [x] Users can create, view (index and show), and edit songs
- [x] Adequate styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds to demonstrate the feature

**Comment by AAlfarho** [comment]
Great job Jon I really like your new splash screen it gives a lot of punch to your site.
Just a couple of things.
+ I noticed that in your play button, the _triangle_ is not centered, is this expected?
+ There is no error message displayed when the title name is no longer than x length, let's tackle this.
+ For testing purposes is ok to let the user upload any file, are we planning on only allowing certain files as media files?
+ When deleting a song I noticed, we are destroying immediately the resource, what do you think about a confirm dialog?
+ I couldn't find the show for the songs, are the only going to be displayed in the feed?

**Comment by jonjonray** [comment]
completed

**Comment by AAlfarho** [comment]
Great job, the new look and feel on the nav bar and the right side pane looks smoother.
Good UX choice in letting the user now that the title of the file is too short.
Last couple of details.
+ Lets implement `esc` to hide the input field when editing a song's title.
+ I noticed that when navigating to `/#/songs/` you are executing 2 ajax requests to fetch all users and songs, that looks OK, given that you require that information, however when clicking on a song you are re-fetching the same data, is this expected?

**Comment by jonjonray** [comment]
Both of those issues are now resolved. Should be all set now.

**Comment by AAlfarho** [comment]
Great job!
MPV is complete.
